"""
gmail_sender.py — sends the feed digest as a newsletter-style HTML email via Gmail SMTP.

Setup (one-time):
  1. In your Google account → Security → 2-Step Verification → ON
  2. Then: Security → App passwords → create one for "Mail"
  3. Copy the 16-char password into .env as GMAIL_APP_PASSWORD

Cost: Free (Gmail SMTP is free up to 500 emails/day).
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

from config import GMAIL_USER, GMAIL_APP_PASSWORD, GMAIL_TO, log


# ── HTML email template ────────────────────────────────────────────────────────

def _build_html(posts: list[dict], date_str: str) -> str:
    """Builds a clean newsletter-style HTML email body."""

    cards = ""
    for i, post in enumerate(posts, 1):
        tags_html = ""
        if post.get("tags"):
            tags_html = "".join(
                f'<span style="background:#f0f0f0;border-radius:4px;padding:2px 8px;'
                f'margin-right:4px;font-size:12px;color:#555;">{t}</span>'
                for t in post["tags"]
            )
            tags_html = f'<div style="margin:10px 0 0;">{tags_html}</div>'

        # Members-only badge
        member_badge = ""
        if post.get("is_member_only"):
            member_badge = (
                '<span style="background:#FFF3CD;color:#856404;border-radius:4px;'
                'padding:2px 8px;font-size:11px;font-weight:600;margin-left:8px;">'
                '⭐ Members Only</span>'
            )

        # Freedium link button (for members-only articles)
        freedium_btn = ""
        if post.get("is_member_only") and post.get("freedium_url"):
            freedium_btn = f"""
            <a href="{post['freedium_url']}"
               style="display:inline-block;background:#6C63FF;color:#fff;
                      text-decoration:none;padding:9px 20px;border-radius:6px;
                      font-size:14px;font-weight:500;margin-left:8px;">
              🆓 Read free →
            </a>
            """

        cards += f"""
        <div style="border:1px solid #e8e8e8;border-radius:10px;padding:24px;
                    margin-bottom:20px;background:#fff;">
          <p style="margin:0 0 4px;font-size:12px;color:#888;font-weight:500;
                    text-transform:uppercase;letter-spacing:.5px;">#{i}{member_badge}</p>
          <h2 style="margin:0 0 4px;font-size:20px;color:#111;line-height:1.3;">
            {_esc_html(post['title'])}
          </h2>
          <p style="margin:0 0 14px;font-size:13px;color:#666;">
            by {_esc_html(post.get('author', 'Unknown'))}
          </p>
          <p style="margin:0;font-size:15px;color:#333;line-height:1.65;">
            {_esc_html(post.get('summary', ''))}
          </p>
          {tags_html}
          <div style="margin:18px 0 0;">
            <a href="{post['url']}"
               style="display:inline-block;background:#1a8917;color:#fff;
                      text-decoration:none;padding:9px 20px;border-radius:6px;
                      font-size:14px;font-weight:500;">
              Read on Medium →
            </a>
            {freedium_btn}
          </div>
        </div>
        """

    return f"""
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,
             'Segoe UI',Helvetica,Arial,sans-serif;">
  <div style="max-width:620px;margin:0 auto;padding:32px 16px;">

    <!-- Header -->
    <div style="text-align:center;margin-bottom:32px;">
      <div style="font-size:28px;font-weight:700;color:#1a8917;letter-spacing:-0.5px;">
        Medium Daily Digest
      </div>
      <div style="font-size:14px;color:#888;margin-top:4px;">{date_str}</div>
      <div style="font-size:14px;color:#555;margin-top:8px;">
        Here are <strong>{len(posts)}</strong> picks from your feed, summarized for you.
      </div>
    </div>

    <!-- Post cards -->
    {cards}

    <!-- Footer -->
    <div style="text-align:center;margin-top:32px;font-size:12px;color:#aaa;">
      Generated by your Medium Agent &nbsp;·&nbsp;
      <a href="https://medium.com/" style="color:#aaa;">Open Medium →</a>
    </div>

  </div>
</body>
</html>
"""


def _build_plain(posts: list[dict], date_str: str) -> str:
    """Plain-text fallback for email clients that don't render HTML."""
    lines = [f"MEDIUM DAILY DIGEST — {date_str}", "=" * 50, ""]
    for i, post in enumerate(posts, 1):
        member_tag = " [⭐ Members Only]" if post.get("is_member_only") else ""
        lines += [
            f"#{i}  {post['title']}{member_tag}",
            f"    by {post.get('author', 'Unknown')}",
            f"    {post.get('summary', '')}",
            f"    Medium: {post['url']}",
        ]
        if post.get("is_member_only") and post.get("freedium_url"):
            lines.append(f"    Free:   {post['freedium_url']}")
        lines.append("")
    lines.append("Generated by your Medium Agent.")
    return "\n".join(lines)


# ── Send ───────────────────────────────────────────────────────────────────────

def send_feed_digest(posts: list[dict]) -> bool:
    """
    Sends the feed digest newsletter to GMAIL_TO.
    Returns True on success.
    """
    if not posts:
        log.info("No feed posts to email.")
        return False

    date_str = datetime.now().strftime("%B %d, %Y")
    subject  = f"📰 Your Medium Digest — {date_str} ({len(posts)} posts)"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = GMAIL_USER
    msg["To"]      = GMAIL_TO

    msg.attach(MIMEText(_build_plain(posts, date_str), "plain"))
    msg.attach(MIMEText(_build_html(posts, date_str),  "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_USER, GMAIL_TO, msg.as_string())
        log.info(f"Email sent to {GMAIL_TO} with {len(posts)} posts.")
        return True
    except Exception as e:
        log.error(f"Gmail send failed: {e}")
        return False


def _esc_html(text: str) -> str:
    return (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
    )
